# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='date_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hire',
            name='date_out',
            field=models.DateField(),
        ),
    ]
