# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopages', '0002_infopage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='slug',
            field=models.SlugField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
