# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tech.TechTag'),
        ),
    ]
