# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_hire_itemhire'),
    ]

    operations = [
        migrations.AddField(
            model_name='techitem',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
