# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0005_auto_20170426_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techitem',
            name='image',
            field=models.URLField(),
        ),
    ]
