# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0006_auto_20170426_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='techitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
