# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_techitem_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techitem',
            name='tags',
        ),
        migrations.DeleteModel(
            name='TechTag',
        ),
    ]
