# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0008_auto_20180217_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='total_hire_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
