# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0009_hire_total_hire_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemhire',
            name='hire',
        ),
        migrations.RemoveField(
            model_name='itemhire',
            name='item',
        ),
        migrations.DeleteModel(
            name='Hire',
        ),
        migrations.DeleteModel(
            name='ItemHire',
        ),
    ]
