# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0010_auto_20180217_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='techitem',
            name='user_guide',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='techitem',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
